WIDTH: 640 #1080 # 1280
HEIGHT: 480 #1920 # 720
PLAY_DIR: play_files
CONFIDENCE_THRESHOLD: 0.5
NEW_IMAGES_MEMMAP_PATH: _current_frames.dat
ALPHA: 0.5
CAPTURE_DURATION: 2 # seconds
FPS: 15
debug: False
